using Yuri.Modules.FastFlags;

namespace Yuri.Modules.ClientSettings;

/// <summary>RSetDetail(i): the per-row explainers, keyed rows first and the generic text last, then the file line, the override note, the values and the staged note.</summary>
public static class RSetDetail
{
    static readonly Dictionary<string, string> Keyed = new()
    {
        ["logorst"] = "Puts both apps' logo art and both shortcut icons back, without touching any other client setting - that is the whole reason it is its own button rather than part of REVERT SETTINGS.  Every file replaced is copied aside before it is overwritten, and each shortcut's previous IconLocation is recorded before it is changed, so this restores what was actually there rather than guessing at Roblox's defaults. Anything with no backup held is left alone instead of overwritten with a guess.",
        ["fps"] = "The frame rate the client aims for. Unlike everything else in this panel, this one does not have to wait for a restart.  The value behind it is DFIntTaskSchedulerTargetFps, and the D on the front is the point: in Roblox's flag system a D-prefixed value is DYNAMIC - the kind Roblox itself can push to a client that is already running. The task scheduler re-reads it as it runs, so writing it into a live client takes effect on the next frame. APPLY does that as well as writing the file, and reads the value back afterwards to confirm it actually took rather than assuming the write was enough.  ABOVE 240 IS DIFFERENT, AND IT WILL NOT GO LIVE. The ceiling is held by FFlagTaskSchedulerLimitTargetFpsTo2402, which has no D prefix - it is read once when the process starts. Writing it afterwards puts the value in memory and the engine never looks there again, so nothing changes. That is a property of the compiled client, not something a tool outside it can work around.  So: 60, 120, 144 and 240 apply instantly, because they sit under the ceiling and only the dynamic value matters. 250 and above are written and saved, but need one restart before they take. Set them, restart Roblox once, and they hold from then on.  The live write goes to the client the FAST FLAG MANAGER is attached to. It attaches on its own within about a second of a client starting, so this is normally available - but with several clients open it is the selected one that changes, not all of them.  MAX is 9999, not infinity - Roblox wants a number.",
        ["gmode"] = "UserGameSettings.GraphicsOptimizationMode - the client's own OPTIMIZE FOR choice, three ways: PERFORMANCE favours frames, QUALITY favours detail, BALANCED sits between. Roblox publishes the three names and nothing more, so treat it as the same pick the in-experience graphics menu offers rather than a separate effect; MAX QUALITY, the row above, is the ceiling that pick works under. Read at launch like the rest of this group.",
        ["shiftlock"] = "UserGameSettings.ControlMode - the SHIFT LOCK SWITCH toggle in the client's settings. ON is MouseLockSwitch, which lets shift lock be turned on and off in game; OFF is the classic camera, moved by holding the right mouse button. An experience that disables shift lock still wins. The file stores the enum's index, and the index changed in build 598 - this writes the current one.",
        ["cammode"] = "UserGameSettings.ComputerCameraMovementMode - the CAMERA MODE pick. DEFAULT is classic; CLASSIC keeps the camera where you put it and does not turn as you walk left or right; FOLLOW turns with you; ORBITAL fixes the camera's height and lets it circle; CAMERA TOGGLE locks and frees rotation with the right mouse button. An experience that forces a camera mode still wins. The CURSOR module's CAMERA TOGGLE slot is the crosshair that last mode draws.",
        ["movemode"] = "UserGameSettings.ComputerMovementMode - how the character is driven on a computer. DEFAULT is keyboard and mouse; KEYBOARD & MOUSE says so explicitly; CLICK TO MOVE walks the character to wherever you right-click, with the keyboard still working alongside it. An experience that forces a movement mode still wins.",
        ["fullscr"] = "UserGameSettings.Fullscreen - whether the client opens full screen, the same state the F11 key and the menu toggle switch while you play. ON opens full screen, OFF opens in a window; START MAXIMIZED, the row below, decides the size of that window. Read at launch, so a client already open keeps what it has until it restarts.",
        ["startmax"] = "UserGameSettings.StartMaximized - whether a windowed client opens maximised. Roblox stores the last window position and size beside it and this row leaves those alone; it only decides whether the frame is maximised when the client appears. A full-screen client has no frame, so FULL SCREEN ON makes this row inert until it is OFF or KEEP again.",
        ["redmot"] = "UserGameSettings.ReducedMotion - the REDUCED MOTION switch under the client's accessibility settings. ON calms the menu and interface animations, OFF keeps Roblox's own. It reaches the client's interface only, never an experience's own effects.",
        ["uitrans"] = "UserGameSettings.PreferredTransparency - the BACKGROUND TRANSPARENCY slider under accessibility: how see-through the menu and interface backgrounds are. 100% is Roblox's own transparency, 0% makes every background solid, and anything between scales it. The file stores the fraction, 0 to 1, and the slider writes it that way.",
        ["maxq"] = "UserGameSettings.MaxQualityEnabled - the bool the client stores next to its quality level, true when the graphics are pinned at the maximum level available. Roblox's own description says exactly that and no more, so treat it as the top notch of the quality range rather than a separate effect: ON pins it, OFF clears it, and KEEP leaves whatever the client last wrote. It and GRAPHICS QUALITY are one slider seen from two sides, so they follow each other: ON moves the slider to 10, and a slider moved off 10 turns this OFF. FRM QUALITY, set to anything but AUTO, overrides both - the flag pins the engine's level and the slider is ignored. Like the rest of this group it is read once at launch, Roblox has to be closed for the write, and REVERT removes the element so the client puts its own default back.",
        ["gfx"] = "UserGameSettings.SavedQualityLevel - the in-client quality slider, AUTO or 1 to 10, with GraphicsQualityLevel, the level the renderer actually runs at, written alongside it. MAX QUALITY is the same slider's top seen as a switch, so the two follow each other: moving this off 10 turns MAX QUALITY off, and MAX QUALITY ON brings this to 10. FRM QUALITY, set to anything but AUTO, overrides both - that flag pins the engine's level and the slider is ignored, so this row goes inert until FRM is back on AUTO. The QUALITY PRESET sets this row rather than FRM.",
        ["frm"] = "DFIntDebugFRMQualityLevelOverride - the engine's own quality ladder, 1 to 21, pinned directly. It is an OVERRIDE: while it is set the client's slider is ignored, so GRAPHICS QUALITY and MAX QUALITY go inert and are not written until this is back on AUTO. The QUALITY PRESET no longer sets it - the presets use the client's own settings and leave this to you - so it is the one row here for a level the slider cannot reach on its own.",
        ["shmap"] = "FIntRenderShadowmapResolution - the size of the shadow map, and so how crisp a shadow's edge is; larger costs GPU. It only means something while there are shadow maps to size: with SHADOWS OFF there are none, and LIGHTING TECHNOLOGY VOXEL draws voxel shadows with no map at all, so either of those makes this row inert until it changes.",
        ["logo"] = "BROWSE picks an image, then APPLY writes it - picking alone changes nothing on disk. One image goes to two different places, because the Roblox logo is not one thing.  1. THE ART INSIDE THE CLIENT. Roblox has never published the name of its logo asset and it has moved between builds, so this does not assume one - it searches the client's own texture folders for every PNG whose filename says it is a logo. Originals are copied aside first and REVERT puts them all back.  2. THE DESKTOP, TASKBAR AND START ICON. That one is not a texture at all, so no file swap under content\\ could ever reach it - it is the SHORTCUT's own icon. Every .lnk carries an IconLocation, and pointing that at a new file changes the icon everywhere the shortcut appears, without touching anything inside the Roblox install. Windows wants an .ico rather than a .png there, so your image is converted to a 256px icon automatically - no converter site and no Resource Hacker. Found  Roblox shortcut(s) on this machine. A Roblox update rewrites its own shortcuts, so press APPLY again after one; REVERT restores each shortcut's previous icon exactly, because the old value is recorded before the first change.  Roblox has never published the name of its logo asset and it has moved between builds, so this does not assume one. It searches the client's own texture folders for every PNG whose filename says it is a logo. Originals are copied aside first and REVERT puts them all back.  RIGHT NOW NO TEXTURE MATCHES, so APPLY would change the shortcut icon only. Press BROWSE again: when the name search comes up empty it opens a second dialog straight into the client's textures folder and lets you point at the exact file to replace. That choice is stored relative to content\\textures, so it applies to every installed version and survives Roblox updates.",
    };
    public static void Open(int i)
    {
        if (i < 1 || i > RSet.Opts.Count) return;
        var o = RSet.Opts[i - 1];
        string w;
        if (Keyed.TryGetValue(o.K == "logos" ? "logo" : o.K, out var kt)) w = kt;
        else if (o.Ui == "file") w = "BROWSE picks a file; the client's own is kept and can be restored.";
        else if (o.Ui == "action") w = "A one-shot action rather than a setting.";
        else if (o.Ui == "preset") w = "HIGH is every graphics row at its maximum. MEDIUM is a balance. LOW is the cheapest the client will render, with the frame rate uncapped - the point of the lowest tier is the highest frame rate. All three set the rendering, lighting, texture, mesh, anti-aliasing, framerate cap, scaling, shadow and post-processing rows, and the client's own quality settings: GRAPHICS QUALITY, MAX QUALITY and GRAPHICS MODE - HIGH pins the slider at 10 with MAX QUALITY ON and QUALITY mode, LOW sits at 1 with PERFORMANCE mode. They put FRM QUALITY back to AUTO rather than setting it: that row is the override that ignores the slider, and a preset that set both was writing one of them for nothing. They leave the font, master volume, mouse sensitivity and the window and control rows exactly as you set them: those are yours, not quality. Staged like everything else here - press APPLY to write it. Change any row afterwards and the preset simply stops being marked, because it is read back from the rows rather than remembered.";
        else if (o.Ui == "slider") w = "Moves the slider to pick a value.";
        else w = "The chip on the right opens the list of values.";
        if (o.Xml is not null && o.Xml != "") w += "  Writes " + o.Xml + " into the client settings file, GlobalBasicSettings.";
        else if (o.Ui is not "file" and not "action" and not "preset") w += "  Writes fast flags into ClientAppSettings.";
        string ov = RSet.RowOverride(o);
        if (ov != "") w = "OVERRIDDEN RIGHT NOW by " + ov + ". The pick below is kept and comes back the moment that changes.  " + w;
        if (o.V.Count > 0) { string vs = string.Join(", ", o.V.Take(6)) + (o.V.Count > 6 ? ", ..." : ""); w += "  Values: " + vs + "."; }
        if (o.Ui != "action") w += "  Staged only - nothing reaches the client until APPLY.";
        Detail.OpenSheet(o.N, o.H, w, "CLIENT SETTINGS");
    }
}