using Yuri.Core;
using Yuri.Gfx;
using static Yuri.Gfx.Col;
using static Yuri.Gfx.Ease;
using static Yuri.Gfx.G;
using static Yuri.Gfx.Tex;
using static Yuri.Shell.Hub.HubUI;

namespace Yuri.Shell.Hub;

public sealed class TutStep
{
    public int Tab, Mod = -1; public string Ttl = "", Glyph = "", Kick = "", View = "", Card = ""; public bool Cur, Prof, Rail;
    public string[] Body = Array.Empty<string>();
    public Func<HubLayout, double[]?>? Anchor; public Func<HubLayout, double>? Ffs, Crs, Rss, Sps; public Action? Det;
    public List<string>? Wrap; public double WrapW;
}

/// <summary>TutBuild: the sixty steps of the tour, text and anchors as the .ahk lays them out.</summary>
public static partial class Tut
{
    static List<TutStep> Build()
    {
        var st = new List<TutStep>();
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "WELCOME TO YURI", Glyph = "brand", Body = new[] { "This is a hub of tools for Roblox: fast flags, cursors, client", "settings, saved places and accounts, device tweaks and a", "script runner.", "", "This tour walks through every part of it, control by control.", "It takes about ten minutes, opens panels and sheets so each", "step is looking at the real thing, and never applies, injects", "or launches anything. NEXT walks on, BACK returns, SKIP leaves", "at any time - and a click on the lit control counts as NEXT." } });
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "THE SIDEBAR", Glyph = "nav", Kick = "SIDEBAR", Cur = true, Anchor = HL => new[] { HL.sbx, HL.NavY(1) - 4, HL.sbw, HL.NavY(6) + HL.nvh - HL.NavY(1) + 4 }, Body = new[] { "The six entries down the left are the hub's tabs. DASHBOARD is", "the overview; INTEGRATIONS holds the modules - the tools", "themselves; SCRIPT HUB writes, checks and runs AutoHotkey", "scripts of your own; SETTINGS is how the hub looks and behaves;", "CREDITS and UPDATE LOGS are what they say. Click an entry to", "switch; the page slides across." } });
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "THE HEART", Glyph = "brand", Kick = "SIDEBAR", Cur = true, Anchor = HL => new[] { HL.sbx + 6, HL.NavY(6) + HL.nvh + 13, HL.sbw - 2, 96 }, Body = new[] { "The heart under the list is a seventh page. Press it and the", "hub opens TOWN: three small pixel towns, picked from the chips", "in the title row - a skyline on its own two-minute day, a city", "street, a village from above. Sparks appear in them now and", "then; take one and the town grows - five levels each, kept for", "good. Press the heart again, or any entry above it, to come", "back." } });
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "WINDOW CONTROLS", Glyph = "grip", Anchor = HL => new[] { HL.brx + 60, HubLayout.pd + 6, HL.bcx - HL.brx - 46, 32 }, Body = new[] { "The six-dot grip is the only place the hub can be dragged from -", "everything else is a control. The dash minimises the hub to a", "small pill you can park anywhere, or hides it to the tray if", "SETTINGS says so; the cross closes it. The hub never takes", "focus from a game, so it can sit over Roblox while you play." } });
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "YOUR PROFILE", Glyph = "people", Kick = "SIDEBAR", Cur = true, Anchor = HL => new[] { HL.sbx, HL.avcy - 30, HL.sbw, 60 }, Body = new[] { "The picture and the name at the foot of the sidebar are yours.", "Click the picture to open the gallery and choose a display", "picture, or to manage the ones you have; the pictures you keep", "are also the reel on the launch gate. Click the name to show", "your bio. The small button beside them opens EDIT PROFILE: the", "name, the bio, the ring drawn round your portrait, and the", "font the hub writes in. SAVE keeps it." } });
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "EDIT PROFILE: PICTURE AND RING", Glyph = "people", Kick = "SIDEBAR  ·  EDIT PROFILE", Prof = true, Anchor = HL => new[] { HubLayout.pd + HubLayout.cw / 2 - 174, HubLayout.pd + HubLayout.ch / 2 - 131, 348, 88 }, Body = new[] { "This is the sheet the small button opens. The portrait on the", "left is your display picture; CHANGE on it opens the gallery.", "The four RING styles beside it decide how the portrait is", "framed - the ring follows it everywhere the hub draws you,", "the sidebar and the launch gate included." } });
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "EDIT PROFILE: NAME AND BIO", Glyph = "list", Kick = "SIDEBAR  ·  EDIT PROFILE", Prof = true, Card = "top", Anchor = HL => new[] { HubLayout.pd + HubLayout.cw / 2 - 174, HubLayout.pd + HubLayout.ch / 2 - 47, 348, 100 }, Body = new[] { "NAME is what the sidebar shows under the picture and what the", "gate greets you by; BIO is the line a click on the name reveals", "- anything you like. Click either to type; the caret goes in." } });
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "EDIT PROFILE: FONT, AND SAVE", Glyph = "palette", Kick = "SIDEBAR  ·  EDIT PROFILE", Prof = true, Anchor = HL => new[] { HubLayout.pd + HubLayout.cw / 2 - 174, HubLayout.pd + HubLayout.ch / 2 + 51, 348, 118 }, Body = new[] { "HUB FONT picks the face the hub writes in - eight choices, from", "the plain to the loud; the change applies everywhere at once.", "SAVE keeps the whole sheet; the cross at the top right closes", "it without saving, and so does a click anywhere outside it." } });
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "DASHBOARD: THE THREE TILES", Glyph = "gauge", Anchor = HL => new[] { HL.ctx, HL.sty, HL.ctw, HL.sth }, Body = new[] { "SESSION is how long this run of the hub has been open. TOTAL", "TIME is every session added together, and DAILY AVG is that", "total spread over the days the hub has seen - screen time per", "day. They count whenever the hub is running, game or no game,", "and nothing here needs pressing." } });
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "SCREEN TIME", Glyph = "clock", Anchor = HL => new[] { HL.ctx, HL.gy, HL.ctw, HL.gh - 12 }, Body = new[] { "One bar per hour of today: the accent is time the hub was open,", "amber over it is time a system was armed as well. The current", "hour is lit, with its figure at the right." } });
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "WHAT'S NEW, AND UPDATES", Glyph = "news", Anchor = HL => new[] { HL.ctx, HL.ly, HL.ctw - 192, Math.Max(120, HubLayout.pd + HubLayout.ch - 34 - HL.ly) }, Body = new[] { "The last seven changes to this build, under the version badge -", "the full list is the UPDATE LOGS tab. CHECK FOR UPDATES asks the", "repository whether a newer build exists and offers to install", "it - the hub restarts into the new version by itself. AUTO", "UPDATE, in SETTINGS, runs that check at launch." } });
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "SYSTEMS AND SCRIPTS", Glyph = "bolt", Anchor = HL => new[] { HL.ctx + HL.ctw - 178, HL.ly, 178, HubLayout.pd + HubLayout.ch - 34 - HL.ly }, Body = new[] { "Two counters. SYSTEMS is how many of the hub's systems are", "armed right now, and a line says which: injected flags, an", "applied cursor, client settings, live scripts. SCRIPTS is how", "many scripts the SCRIPT HUB has placed, and how many of them", "are running. Both turn green when something is live." } });
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "OPEN ROBLOX, AND THIS TOUR", Glyph = "dart", Cur = true, Anchor = HL => new[] { HL.ctx + HL.ctw - 294, HL.cty - 9, 262, 36 }, Body = new[] { "OPEN ROBLOX launches the client the way its own shortcut does;", "the lamp at its right end is green while a client is running.", "With AUTO INJECT armed in the flag manager, staged flags are", "written into the client a few seconds after it starts. The", "launch gate you saw at start-up has the same button, beside OPEN", "HUB and ACCOUNTS. TUTORIAL plays this tour again, from the top." } });
        st.Add(new TutStep { Tab = 2, Mod = 0, Ttl = "INTEGRATIONS: THE MODULE RAIL", Glyph = "rail", Cur = true, Anchor = HL => new[] { HL.mdx - 6, Tabs.Integrations.MdRailTop(HL), HL.mdw + 12, Tabs.Integrations.MdRailVis(HL) }, Body = new[] { "Each card in this rail is a module. Click one and its systems", "open in the panel to the right; click it again to close. The", "cards that write Roblox's own files come first - FAST FLAG", "MANAGER, CURSOR, CLIENT SETTINGS, SPECIAL - and the two that", "touch the machine itself, DEVICE OPTIMIZATIONS and LOGIN ITEMS,", "sit at the foot. The rail scrolls when it is taller than the", "window, and the dot on a card is its state: lit when the module", "is armed or applied." } });
        st.Add(new TutStep { Tab = 2, Mod = 1, Ttl = "FAST FLAG MANAGER", Glyph = "flag", Anchor = HL => new[] { HL.abx, HL.aby, HL.abw, PanelH(HL) }, Body = new[] { "The most used module. Fast flags are Roblox's own switches -", "graphics, physics, debug views - and this manager stages a", "list of them and delivers it two ways: written straight into", "the running client's memory from this panel, or into the", "settings file Roblox reads at launch, which the CLIENT", "SETTINGS module does. The systems card comes first; the search", "field and the staged list sit under it." } });
        st.Add(new TutStep { Tab = 2, Mod = 1, Ttl = "INJECT AND UNINJECT", Glyph = "bolt", Anchor = HL => FFRows(HL, 1, 1), Body = new[] { "INJECT writes every staged value into the running client's", "memory. Nothing touches the disk, so the set lasts until the", "client closes, and a flag this client does not carry is", "reported as failed rather than dropped. UNINJECT puts every", "original value back. The button reads NO RBX until a client is", "running; CLOSE RBX, in the header above, ends the client. With", "several clients open, a strip of tabs over the panel says which", "one INJECT is pointed at - ALL runs the set into every client." } });
        st.Add(new TutStep { Tab = 2, Mod = 1, Ttl = "SINGLETON, RE-APPLY, AUTO INJECT", Glyph = "sliders", Anchor = HL => FFRows(HL, 2, 4), Body = new[] { "Three switches. SINGLETON is how the flag table is found: on,", "by a code signature, fast and the right default; off, by a", "slower sweep that survives an update that moved the code -", "turn it off if injection starts failing after one. RE-APPLY", "holds what you injected: every two seconds it rewrites any", "injected flag Roblox has reset - it never injects on its own.", "AUTO INJECT is the one that does: it waits four seconds after", "a client appears, then injects for you." } });
        st.Add(new TutStep { Tab = 2, Mod = 1, Ttl = "CLEAN, AND UPDATE FLAGS", Glyph = "tick", Ffs = HL => Modules.FastFlags.FfmPanel.SysRowY(HL, 5) - 12, Anchor = HL => FFRows(HL, 5, 6), Body = new[] { "Two housekeeping actions. CLEAN drops every flag the last", "injection could not find, leaving a set this client actually", "accepts - do it before exporting. UPDATE fetches Roblox's live", "flag list and renames any staged flag that has been retired to", "its closest current name; names still valid are left alone,", "and every rename is written to the UPDATES log." } });
        st.Add(new TutStep { Tab = 2, Mod = 1, Ttl = "PRESETS, AND COMMUNITY FLAGS", Glyph = "folder", Ffs = HL => Modules.FastFlags.FfmPanel.SysTotal(HL), Anchor = HL => FFRows(HL, 7, 9), Body = new[] { "The PRESETS group. INSERT HITBOX replaces the staged set with", "the built-in HITBOX preset - replication and input flags aimed", "at making hits register closer to what you see. INSERT 30HZ", "HITBOX is the same idea tuned around interpolation and a lower", "replication rate. Both replace rather than merge - HISTORY", "keeps a snapshot first. COMMUNITY FLAGS is the browser of sets", "shared by other players; BROWSE opens it, and so does NEXT." } });
        st.Add(new TutStep { Tab = 2, Mod = 1, Ttl = "COMMUNITY FLAGS: THE BROWSER", Glyph = "people", Kick = "INTEGRATIONS  ·  FAST FLAG MANAGER  ·  COMMUNITY FLAGS", View = "comm", Card = "bot", Anchor = HL => SheetHead(HL), Body = new[] { "This is the panel BROWSE opens. It is drawn from a cache on", "disk the moment it opens, then checks the repository in the", "background and swaps in anything that changed; REFRESH does", "that on demand. Under the banner sits one card per game,", "each with folders of flag sets and the name of whoever shared", "them. INSERT on a set replaces the staged list with it, after a", "HISTORY snapshot, and closes the browser so you land on the", "result." } });
        st.Add(new TutStep { Tab = 2, Mod = 1, Ttl = "DATABASE, IMPORT, EXPORT, CLEAR, LOGS", Glyph = "folder", Anchor = HL => new[] { HL.abx - 4, HL.ffby - 6, 410, 38 }, Body = new[] { "DATABASE searches every flag the hub knows. IMPORT takes a JSON", "file - or whatever is on the clipboard, if you cancel the", "picker; EXPORT writes the staged list out the same way. CLEAR", "empties it. LOGS opens the record of what every injection,", "update and clear did, and HISTORY inside it keeps a snapshot", "before every clear, import, preset and community insert, so", "nothing is lost for good." } });
        st.Add(new TutStep { Tab = 2, Mod = 1, Ttl = "THE FLAG DATABASE", Glyph = "search", Kick = "INTEGRATIONS  ·  FAST FLAG MANAGER  ·  DATABASE", View = "db", Card = "bot", Anchor = HL => SheetHead(HL), Body = new[] { "The FLAG DATABASE, as DATABASE opens it: every name the hub", "knows, tens of thousands of them, with a filter field at the", "top. Type to narrow the list; ENTER stages the first match, a", "click stages any row, and rows already in your list say so.", "The cross, or ESC, closes it. A value is checked as it goes", "in - one that does not fit the flag's type is refused." } });
        st.Add(new TutStep { Tab = 2, Mod = 1, Ttl = "STAGING FLAGS", Glyph = "list", Anchor = HL => new[] { HL.abx + 8, HL.ffqy - 6, HL.abw - 16, HL.fflh + 44 }, Body = new[] { "Type a flag name in the field and the plus beside it stages", "it; type anything else and the list is filtered by it. Each", "staged row has its value - click it to edit, click a bool to", "flip it - a type pill, and a pip on the left that is the row's", "own ON/OFF: a flag switched off stays in the list but is never", "applied. A right-click on a field gives cut, copy and paste.", "Values that do not fit the name are refused on the way in." } });
        st.Add(new TutStep { Tab = 2, Mod = 1, Ttl = "LOGS: INJECTION, UPDATES, HISTORY", Glyph = "list", Kick = "INTEGRATIONS  ·  FAST FLAG MANAGER  ·  LOGS", View = "log", Card = "bot", Anchor = HL => SheetHead(HL), Body = new[] { "LOGS has three tabs. INJECTION lists what the last injections", "did, flag by flag - written, failed, restored. UPDATES is the", "record UPDATE FLAGS leaves: every rename, and every name it", "could not place, with UNDO. HISTORY is the snapshots: one is", "taken before CLEAR, an import, a preset, a community set,", "UPDATE and a delete, and RESTORE puts any of them back." } });
        st.Add(new TutStep { Tab = 2, Mod = 3, Ttl = "CURSOR: FOUR IMAGE SLOTS", Glyph = "pointer", Anchor = HL => CurRows(HL, 1, 4), Body = new[] { "Roblox draws four cursors from four PNG files, and each row", "here is one of them: ARROW, the pointer you see almost all the", "time; SHIFT LOCK, the reticle while shift lock is held; CAMERA", "TOGGLE, the crosshair for camera toggle; and TEXT, the caret", "over chat and text boxes. BROWSE picks an image for a slot -", "square, around 64 pixels, holds up best - and staging it", "changes nothing until APPLY." } });
        st.Add(new TutStep { Tab = 2, Mod = 3, Ttl = "APPLY, RESTORE, FAR CURSOR, AUTO RE-APPLY", Glyph = "bolt", Crs = HL => Modules.Cursor.CurPanel.SysTotal(HL), Anchor = HL => CurRows(HL, 5, 8), Body = new[] { "APPLY copies every staged slot over the files of every Roblox", "install it can find - and into the Modifications store of", "Bloxstrap, Fishstrap or Voidstrap, which the launcher lays over", "the client at every start - backing up whatever was there", "first. RESTORE puts those backups back; it can only undo what", "this hub wrote, and says so when a slot has no original. FAR", "CURSOR also replaces the smaller pointer Roblox draws for", "distant things, from the arrow's image. AUTO RE-APPLY watches", "for a Roblox update, which puts the default files back, and", "rewrites your set afterwards." } });
        st.Add(new TutStep { Tab = 2, Mod = 3, Ttl = "THE PREVIEW CARD", Glyph = "news", Anchor = HL => new[] { HL.abx, HL.ffby, HL.abw, 220.0 }, Body = new[] { "The card under the list is the state of the module. One tile", "per slot shows the image that is staged - or, when nothing is,", "whatever is on disk right now, captioned to say whether that", "is Roblox's own file, a Bloxstrap mod, or a backup this hub", "took. Under the tiles: which installs will be written, how", "many backups are held, and the last thing the module said.", "OPEN FOLDER goes to the cursor files themselves." } });
        st.Add(new TutStep { Tab = 2, Mod = 3, Ttl = "EVERY ROW HAS A STORY", Glyph = "list", Kick = "INTEGRATIONS  ·  CURSOR  ·  DETAIL SHEET", Det = () => Modules.Cursor.CurPanel.OpenDetail(6), Anchor = HL => DetHead(HL), Body = new[] { "Every row in every module opens one of these. Click a row's", "name or its description - not its button - and a sheet arrives", "with the whole story: what the control does, what it touches,", "and what to do when it goes wrong. This one is RESTORE DEFAULT's.", "Long ones scroll, and the round cross is the only thing that", "closes it, so a stray click cannot take away what you opened." } });
        st.Add(new TutStep { Tab = 2, Mod = 4, Ttl = "CLIENT SETTINGS", Glyph = "sliders", Anchor = HL => new[] { HL.abx, HL.cty + 28, HL.abw, HL.aby + RSetY(HL, 3) + HL.rsrh + 2 - (HL.cty + 28) }, Body = new[] { "The client's own files, written on disk rather than in memory.", "The rows come in four groups, with one APPLY in the header for", "all of them - it reads REVERT once the module is live. ACTIONS", "come first: APPLY SETTINGS and REVERT SETTINGS, which puts", "every row back to the Roblox default, and QUALITY PRESET,", "which sets every graphics row at once - HIGH, MEDIUM or LOW.", "Roblox has to be closed for a write; the file is only writable", "then." } });
        st.Add(new TutStep { Tab = 2, Mod = 4, Ttl = "CLIENT FILES", Glyph = "sliders", Rss = HL => RSetY(HL, RSIdx("render")) - 12, Anchor = HL => RSRows(HL, RSIdx("render"), RSIdx("render") + 2), Body = new[] { "The CLIENT FILES group is the settings Roblox keeps in its own", "files. RENDERING MODE, which graphics api the client asks for;", "LIGHTING TECHNOLOGY; FRM, TEXTURE and MESH QUALITY;", "ANTI-ALIASING; FRAMERATE CAP; DISPLAY SCALING; SHADOWS and", "SHADOW DETAIL; POST-PROCESSING. Then three that swap files", "rather than values - ROBLOX FONT, ROBLOX LOGO and ROBLOX STUDIO", "LOGO take a file of your own - and RESTORE LOGOS puts the", "originals back. A row left at its first choice - AUTO, KEEP or", "DEFAULT - is not written at all." } });
        st.Add(new TutStep { Tab = 2, Mod = 4, Ttl = "THE CLIENT SETTINGS FILE", Glyph = "sliders", Rss = HL => RSetY(HL, RSIdx("gfx")) - 12, Anchor = HL => RSRows(HL, RSIdx("gfx"), RSIdx("gfx") + 2), Body = new[] { "The CLIENT SETTINGS FILE group writes the XML file Roblox keeps", "its in-game menu choices in - the list scrolls. Graphics first:", "GRAPHICS QUALITY, the in-client slider or AUTO; MAX QUALITY,", "the slider's top as a switch - the two follow each other; and", "GRAPHICS MODE, what it optimises for. Then MASTER VOLUME,", "MOUSE SENSITIVITY, SHIFT LOCK SWITCH, CAMERA MODE, MOVEMENT", "MODE, FULL SCREEN, START MAXIMIZED, REDUCED MOTION and UI", "TRANSPARENCY - each reading the value the file holds now.", "KEEP leaves a value alone; REVERT removes what this module", "wrote, so Roblox supplies its own defaults again." } });
        st.Add(new TutStep { Tab = 2, Mod = 4, Ttl = "FAST FLAGS, FROM HERE", Glyph = "flag", Rss = HL => Modules.ClientSettings.RSet.Total(HL.rsrg), Anchor = HL => RSRows(HL, RSIdx("fxedit"), RSIdx("src")), Body = new[] { "The FAST FLAGS group is the second way flags reach the client:", "through the settings file, read at launch, rather than memory.", "EDIT FAST FLAGS opens a page of its own - a list you add names", "and values to, with the same DATABASE search behind it. FLAG", "SOURCE decides which half of this module reaches the file:", "MIX, the systems rows only, or the edited flags only." } });
        st.Add(new TutStep { Tab = 2, Mod = 4, Ttl = "THE STATE CARD", Glyph = "gauge", Anchor = HL => new[] { HL.abx, HL.ffby, HL.abw, (double)Modules.ClientSettings.RSet.CH }, Body = new[] { "The STATE card is the module's readout. The dial counts the", "rows that are set and fills once they are applied; FLAGS,", "FILE, BACKUP and WRITES say what will be written where, and", "whether the original file is held. ALL AUTO puts every row", "back to its first choice without touching the disk; OPEN FILE", "opens the client settings file itself." } });
        st.Add(new TutStep { Tab = 2, Mod = 5, Ttl = "SPECIAL FEATURES: SEVENTEEN SWITCHES", Glyph = "pin", Anchor = HL => SPFRows(HL, 1, 3), Body = new[] { "Seventeen switches, three at a time - the list scrolls. DISCORD", "ACTIVITY shows the game you are in on your Discord profile,", "with chips for your account, a join link and whether Roblox is", "the focused window. SHOW SERVER REGION reads the server out of", "the client log and looks up where it is hosted. AUTO-REGION", "FINDER rejoins - up to fifteen times - until the server is", "close to you; it is the one switch that restarts Roblox on you." } });
        st.Add(new TutStep { Tab = 2, Mod = 5, Ttl = "MATCHMAKING, INSTANCES, FPS", Glyph = "pin", Sps = HL => Modules.Special.SpfPanel.spfrg * 3, Anchor = HL => SPFRows(HL, 4, 6), Body = new[] { "BETTER MATCHMAKING, marked experimental, never rejoins anyone:", "each join teaches it how far one server is, and later joins", "ask for one it already measured as close. MULTI-ROBLOX", "INSTANCES lets several clients run at once, one per account -", "launch them from the website, not the shortcut. FPS BOOST", "buys frames without touching a graphics setting, and its row", "reports what it managed and where the bottleneck sits." } });
        st.Add(new TutStep { Tab = 2, Mod = 5, Ttl = "CRASH HANDLER, MEMORY TRIMMER", Glyph = "pin", Sps = HL => 9999, Anchor = HL => SPFRows(HL, 7, 8), Body = new[] { "DISABLE CRASH HANDLER closes RobloxCrashHandler.exe, the", "watchdog Roblox starts beside every client; if the client then", "crashes it simply closes, with no crash box. MEMORY TRIMMER", "empties the client's working set on a schedule - its two chips", "set how often, and a size the client must reach first. The", "client faults the pages straight back, so expect a hitch at", "each trim; it is for machines that are short of RAM." } });
        st.Add(new TutStep { Tab = 2, Mod = 5, Ttl = "SERVER, HOME APP, CLEANER", Glyph = "pin", Sps = HL => Modules.Special.SpfPanel.spfrg * 8, Anchor = HL => SPFRows(HL, 9, 11), Body = new[] { "SERVER DETAILS keeps the type, uptime and id of the server", "you are in and a history of every one you joined - REJOIN", "LAST and COPY LINK are its chips. NO DESKTOP APP closes the", "client when you leave a game instead of showing the home", "app. ROBLOX CLEANER deletes Roblox logs and cache older", "than the age its chip shows, at every launch or on CLEAN NOW." } });
        st.Add(new TutStep { Tab = 2, Mod = 5, Ttl = "STARTUP, THEME, OLD SOUNDS", Glyph = "pin", Sps = HL => Modules.Special.SpfPanel.spfrg * 11, Anchor = HL => SPFRows(HL, 12, 14), Body = new[] { "LAUNCH ON STARTUP puts YURI in the Windows startup list.", "ROBLOX APP THEME forces the app light or dark - the chip", "picks which. OLD CHARACTER SOUNDS restores the 2014 walk,", "jump and get-up sounds in every Roblox install; the original", "files are kept beside them and put back when it is off." } });
        st.Add(new TutStep { Tab = 2, Mod = 5, Ttl = "BACKGROUND, DEATH SOUND, EMOJI", Glyph = "pin", Sps = HL => 9999, Anchor = HL => SPFRows(HL, 15, 17), Body = new[] { "OLD AVATAR BACKGROUND brings back the 2020 avatar editor", "scene. CUSTOM DEATH SOUND replaces the oof with any .ogg you", "pick - PICK FILE is its chip. EMOJI FONT swaps the emoji for", "Catmoji or the Windows 11, 10 or 8 set; its chip cycles them.", "All three fetch what they need once, and re-apply after a", "Roblox update on their own." } });
        st.Add(new TutStep { Tab = 2, Mod = 5, Ttl = "ACCOUNTS, PLACES, AND THE LINK FIELDS", Glyph = "folder", Anchor = HL => new[] { HL.abx, HL.aby + 134, HL.abw, Modules.Special.SpfPanel.spfh - 134 }, Body = new[] { "Under the switches, two libraries and two link fields.", "ACCOUNTS keeps Roblox accounts and can launch a client already", "signed in as any of them; SAVED PLACES keeps places and", "private servers, with live player counts, ratings and a", "picture reel, and launches them in a click. GAME LINK and", "PRIVATE SERVER LINK take a link or a place id; the button", "beside each reads JOIN, or HUNT when AUTO-REGION FINDER is on,", "and rerolls that place until the server is close." } });
        st.Add(new TutStep { Tab = 2, Mod = 5, Ttl = "ACCOUNTS", Glyph = "people", Kick = "INTEGRATIONS  ·  SPECIAL FEATURES  ·  ACCOUNTS", View = "acct", Card = "bot", Anchor = HL => SheetHead(HL), Body = new[] { "The account manager, as ACCOUNTS opens it - and as the launch", "gate's ACCOUNTS button does. BROWSER LOGIN opens a clean,", "signed-out browser window to sign in on and picks the session", "up; ADD FROM CLIPBOARD takes a .ROBLOSECURITY cookie by hand.", "Each saved account gets a LAUNCH TARGET - a place id, a game", "link, a private server link - and a LAUNCH button that opens a", "client already signed in as it, one per account with MULTI-", "ROBLOX INSTANCES on. A saved cookie signs in with no password:", "keep this machine yours." } });
        st.Add(new TutStep { Tab = 2, Mod = 5, Ttl = "LIVE", Glyph = "gauge", Anchor = HL => new[] { HL.abx, HL.aby + Modules.Special.SpfPanel.spfh + 12, HL.abw, 96 }, Body = new[] { "The LIVE strip is what the switches are seeing right now: the", "GAME you are in and its place id; the REGION the server is", "hosted in and how far away it is; HOME, the region the finder", "and the matchmaker measure against; and DISCORD, whether the", "presence is linked. The dot breathes green in a game, amber", "armed and waiting, grey when the features are off." } });
        st.Add(new TutStep { Tab = 2, Mod = 6, Ttl = "DEVICE OPTIMIZATIONS", Glyph = "chip", Rail = true, Anchor = HL => DOPRows(HL), Body = new[] { "Windows-side tweaks that help a game run, in five groups, each", "its own switch: INPUT LATENCY - 1:1 pointer, no acceleration,", "shorter input queues; SYSTEM TIMERS; NETWORK STACK - throttling", "and Nagle off, adapter offloads off; POWER & USB - power", "throttling and selective suspend off, the high performance", "plan; GPU & SCHEDULING. Every switch asks for administrator", "rights, and the rows marked RESTART need one before they show." } });
        st.Add(new TutStep { Tab = 2, Mod = 6, Ttl = "SNAPSHOTS, RE-APPLY, REVERT ALL", Glyph = "chip", Rail = true, Anchor = HL => new[] { HL.abx, HL.aby + Modules.DeviceOpt.DopPanel.Doph + 12, HL.abw, 96 }, Body = new[] { "The card under the rows is the module's ledger. The tally is", "one segment per group, lit as it is applied. The machine was", "captured exactly as it was found before the first change, so", "REVERT ALL puts it back to that, not to one click ago.", "SNAPSHOTS shows each recorded change and can undo it on its", "own; RE-APPLY lights only when a setting has drifted back." } });
        st.Add(new TutStep { Tab = 2, Mod = 7, Ttl = "LOGIN ITEMS", Glyph = "power", Rail = true, Anchor = HL => new[] { HL.abx, HL.aby, HL.abw, Modules.LoginItems.LgiPanel.Lgih }, Body = new[] { "Programs that come and go with Roblox. The strip at the top is", "the lifeline: ROBLOX at one end, and every app you add strung", "along it, lit as it runs. ADD APP takes anything - a program, a", "shortcut, a script, a document - and each gets two switches:", "OPENS starts it when a client appears, CLOSES shuts it once the", "last one is gone. A change has to hold a few seconds first, so", "a client restarting mid-update never closes anything." } });
        st.Add(new TutStep { Tab = 2, Mod = 7, Ttl = "ARMED, ADD APP, OPEN ALL, CLOSE ALL", Glyph = "power", Rail = true, Anchor = HL => new[] { HL.abx, HL.aby + Modules.LoginItems.LgiPanel.Lgih + 12, HL.abw, 96 }, Body = new[] { "ARMED is the master switch: with it off nothing is started or", "stopped, whatever the rows say. ADD APP adds an entry - up to", "eight; OPEN ALL and CLOSE ALL do by hand what the switches do", "on their own. The line at the left is what the watcher last", "did, and the segments beside it are the entries, lit when", "they are set to open or close." } });
        st.Add(new TutStep { Tab = 3, Mod = -1, Ttl = "SCRIPT HUB", Glyph = "code", Anchor = HL => new[] { HL.ctx, HL.cty + 38, HL.ctw, 26.0 }, Body = new[] { "A place to write, check and run AutoHotkey scripts of your", "own. The toolbar: NEW clears the editor; PASTE drops in the", "clipboard; FILE loads an .ahk from disk; CHECK validates the", "script against the AutoHotkey you have installed - v2 first,", "then v1 - and reports on the OUTPUT line; SAVE writes it into", "the hub's scripts folder; EXPORT writes an .AHK or .TXT", "anywhere; SAVED opens that folder; CLEAR empties everything.", "PLACE, at the right, checks it and adds it to the cards below." } });
        st.Add(new TutStep { Tab = 3, Mod = -1, Ttl = "TABS, NAME AND DESCRIPTION", Glyph = "code", Anchor = HL => new[] { HL.ctx, HL.cty + 72, HL.ctw, 54.0 }, Body = new[] { "The editor has tabs - the plus opens another, the cross on a", "tab closes it, and IN MAIN copies a side tab's script into the", "first one. Under them, two fields: the name the placed card", "will carry, and a line of description for it. Click either to", "type; the caret goes straight in." } });
        st.Add(new TutStep { Tab = 3, Mod = -1, Ttl = "THE EDITOR", Glyph = "code", Anchor = HL => new[] { HL.ctx, HL.cty + 134, HL.ctw, 54.0 }, Body = new[] { "Click in the editor and type, or ctrl+V to paste. Comments,", "strings, numbers and commands each get a colour, the gutter", "counts lines, and ESC leaves the field." } });
        st.Add(new TutStep { Tab = 3, Mod = -1, Ttl = "OUTPUT, AND THE PLACED CARDS", Glyph = "bolt", Anchor = HL => new[] { HL.ctx, HL.cty + 134 + 122 + 8, HL.ctw, HL.cty + 134 + 122 + 52 + 64 - (HL.cty + 134 + 122 + 8) }, Body = new[] { "OUTPUT is CHECK's verdict, with the version it validated", "against. PLACED is every script you have placed, a card each:", "a picture you can change, ENABLE to run it and STOP while it", "runs, EDIT to load it back into the editor - where PLACE", "becomes UPDATE - and a cross to remove it. The band scrolls." } });
        st.Add(new TutStep { Tab = 4, Mod = -1, Ttl = "SETTINGS: ACCENT", Glyph = "palette", Anchor = HL => new[] { HL.ctx, HL.setr, HL.ctw, HL.rh }, Body = new[] { "The accent colour runs through every control in the suite -", "six to pick from, and the ring shows which is live. Nothing", "else changes with it: the theme, the opacities and the font", "are their own settings." } });
        st.Add(new TutStep { Tab = 4, Mod = -1, Ttl = "BACKDROP AND ELEMENTS", Glyph = "palette", Anchor = HL => new[] { HL.ctx, HL.setr + (HL.rh + HL.rgap), HL.ctw, 2 * HL.rh + HL.rgap }, Body = new[] { "Two opacities. BACKDROP fades the window's plate; ELEMENTS", "fades the controls drawn on it. Slide either down and a game", "stays visible behind the hub. The swatch further down the page", "previews the pair." } });
        st.Add(new TutStep { Tab = 4, Mod = -1, Ttl = "THEME, AND ARMED TINT", Glyph = "palette", Anchor = HL => new[] { HL.ctx, HL.setr + 3 * (HL.rh + HL.rgap), HL.ctw, HL.rh }, Body = new[] { "DARK and LIGHT swap the base the hub is drawn on. ARMED TINT", "recolours it whenever a system is armed." } });
        st.Add(new TutStep { Tab = 4, Mod = -1, Ttl = "SETTINGS: BEHAVIOUR", Glyph = "cog", Anchor = HL => new[] { HL.ctx, HL.sett, HL.ctw, HL.seth }, Body = new[] { "Four switches. PERFORMANCE turns every effect off and lets the", "hub idle at nothing - use it on a weak machine. ON TOP keeps", "the hub above other windows. MINIMIZE decides whether the dash", "shrinks the hub to the pill or hides it to the tray. AUTO", "UPDATE checks the repository at launch and asks before it", "installs anything." } });
        st.Add(new TutStep { Tab = 4, Mod = -1, Ttl = "THE GALLERY, AND RESET", Glyph = "palette", Anchor = HL => new[] { HL.ctx, HL.setp, HL.ctw, 94.0 }, Body = new[] { "GALLERY is the set of pictures the hub rotates through - on", "the launch gate, under UPDATE LOGS, and on the minimised pill;", "MANAGE opens the grid to add and remove them. LIVE PREVIEW is", "the two opacities and the theme in miniature. RESET APPEARANCE", "puts accent, opacities and theme back to factory: rose,", "100 / 100, dark." } });
        st.Add(new TutStep { Tab = 5, Mod = -1, Ttl = "CREDITS", Glyph = "people", Anchor = HL => new[] { HL.ctx, HL.cty + 34, HL.ctw, 128.0 }, Body = new[] { "Who made it. The card shows a maker's avatar, name and role,", "and the two chips on the rule below switch between ZEAL, who", "designed, built and animated the hub, and LUNARIS, who wrote", "its functions and the fast-flag work." } });
        st.Add(new TutStep { Tab = 5, Mod = -1, Ttl = "FIND THEM", Glyph = "people", Anchor = HL => new[] { HL.ctx, HL.lky - 28, HL.ctw, HL.lkh + 28 }, Body = new[] { "Their links, for whichever maker the chips have picked. ROBLOX", "opens the profile, YOUTUBE the channel, and the DISCORD card", "copies the tag to your clipboard, ready to paste into a search", "- and flashes to say it has." } });
        st.Add(new TutStep { Tab = 6, Mod = -1, Ttl = "UPDATE LOGS", Glyph = "news", Anchor = HL => new[] { HL.ctx, HL.cty + 36, HL.ctw - 232, 122.0 }, Body = new[] { "Everything the hub has shipped, the first release at the top,", "with the build and channel this copy came in. A plus is", "something added; an amber mark is something changed or fixed.", "The list scrolls; the dashboard shows only its last seven." } });
        st.Add(new TutStep { Tab = 6, Mod = -1, Ttl = "THE GALLERY REEL", Glyph = "news", Anchor = HL => new[] { HL.ctx + HL.ctw - 224, HL.cty + 40, 212, HubLayout.pd + HubLayout.ch - HL.cty - 96 }, Body = new[] { "The reel on the right is the gallery, one picture at a time,", "with a counter and a bar filling towards the next. It is the", "same set the launch gate and the minimised pill show; MANAGE,", "in SETTINGS, adds to it and takes pictures out of rotation." } });
        st.Add(new TutStep { Tab = 1, Mod = -1, Ttl = "THAT'S THE TOUR", Glyph = "tick", Body = new[] { "Everything you saw is live: the flags stage, the modules apply,", "the client launches. Three things worth remembering:", "", "REVERT, RESTORE and UNINJECT always exist - nothing here is", "one-way, and HISTORY and SNAPSHOTS keep what came before.", "Any row's name opens a sheet with its full story.", "The TUTORIAL button on the dashboard plays this again.", "", "FINISH returns you to the dashboard." } });
        return st;
    }
}